#!/usr/bin/env python

import sys

from rqt_bag.bag import Bag
from rqt_gui.main import Main

plugin = 'rqt_map_topo.map_topo.MapTopo'
main = Main(filename=plugin)
sys.exit(main.main(standalone=plugin, plugin_argument_provider=MapTopo.add_arguments))